name: 'Terraform Plan Parser'
description: 'Parse Terraform plan diffs and output structured information'
inputs:
  terraform-plan:
    description: 'Terraform plan output to parse'
    required: true
  ignore-resources:
    description: 'JSON array of resource types or specific resources to ignore (e.g. ["null_resource", "null_resource.main", "local_file"])'
    required: false
    default: '[]'
outputs:
  diff-bool:
    description: 'Whether there are any diffs (true/false)'
  diff-resources:
    description: 'JSON array of Terraform resource addresses that have changes'
  diff-raw:
    description: 'Raw Terraform plan output as provided to the action'
  diff-count:
    description: 'Number of resources that have changes'
  diff-json:
    description: 'Complete parse result as JSON including all diff details and structured plan data'
  create-bool:
    description: 'Whether there are any resources to be created (true/false)'
  create-count:
    description: 'Number of resources to be created'
  create-resources:
    description: 'JSON array of resource addresses to be created'
  destroy-bool:
    description: 'Whether there are any resources to be destroyed (true/false)'
  destroy-count:
    description: 'Number of resources to be destroyed'
  destroy-resources:
    description: 'JSON array of resource addresses to be destroyed'
  update-bool:
    description: 'Whether there are any resources to be updated (true/false)'
  update-count:
    description: 'Number of resources to be updated'
  update-resources:
    description: 'JSON array of resource addresses to be updated'
  replace-bool:
    description: 'Whether there are any resources to be replaced (true/false)'
  replace-count:
    description: 'Number of resources to be replaced'
  replace-resources:
    description: 'JSON array of resource addresses to be replaced'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'search'
  color: 'purple'
