name: 'Terraform Plan Inspector'
description: 'Analyze Terraform plan diffs and output structured information'
inputs:
  terraform-plan:
    description: 'Terraform plan output to analyze'
    required: true
  ignore-resources:
    description: 'JSON array of resource types or specific resources to ignore (e.g. ["null_resource", "null_resource.main", "local_file"])'
    required: false
    default: '[]'
outputs:
  diff:
    description: 'Whether there are any diffs (true/false)'
  all-diffs:
    description: 'JSON string containing all diffs found'
  resources:
    description: 'JSON array of Terraform resource names that have changes'
  raw-diffs:
    description: 'Raw Terraform plan output as provided to the action'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'search'
  color: 'purple'