name: 'Terraform Plan Parser'
description: 'Parse Terraform plan diffs and output structured information'
inputs:
  terraform-plan:
    description: 'Terraform plan output to parse'
    required: true
  ignore-resources:
    description: 'JSON array of resource types or specific resources to ignore (e.g. ["null_resource", "null_resource.main", "local_file"])'
    required: false
    default: '[]'
outputs:
  diff-bool:
    description: 'Whether there are any diffs (true/false)'
  diff-resources:
    description: 'JSON array of Terraform resource addresses that have changes'
  diff-raw:
    description: 'Raw Terraform plan output as provided to the action'
  diff-count:
    description: 'Number of resources that have changes'
  diff-json:
    description: 'Complete analysis result as JSON including all diff details and structured plan data'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'search'
  color: 'purple'
