name: Terraform Plan Analysis

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Analyze Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8


    - name: Terraform Init
      run: terraform init
      working-directory: ./example/terraform

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: ./example/terraform

    - name: Analyze Terraform Plan
      id: analyze
      uses: ./
      with:
        terraform-plan: ${{ steps.plan.outputs.stdout }}
        ignore-resources: '["null_resource"]'

    - name: Display Results
      run: |
        echo "Has diff: ${{ steps.analyze.outputs.diff }}"
        echo "Resources changed: ${{ steps.analyze.outputs.resources }}"
        echo "All diffs: ${{ steps.analyze.outputs.all-diffs }}"

    - name: Comment on PR (if PR)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const diff = '${{ steps.analyze.outputs.diff }}';
          const resources = JSON.parse('${{ steps.analyze.outputs.resources }}');
          const allDiffs = JSON.parse('${{ steps.analyze.outputs.all-diffs }}');

          let body = '## Terraform Plan Analysis\n\n';

          if (diff === 'true') {
            body += `✅ **Changes detected** affecting ${resources.length} resources:\n\n`;

            for (const diffItem of allDiffs) {
              const action = diffItem.action;
              const actionEmoji = {
                'create': '➕',
                'update': '🔄',
                'delete': '🗑️',
                'replace': '🔄'
              }[action] || '❓';

              body += `${actionEmoji} **${action.toUpperCase()}**: \`${diffItem.address}\` (${diffItem.resource})\n`;
            }
          } else {
            body += '✅ **No changes detected**';
          }

          body += '\n\n---\n*Generated by Terraform Plan Inspector*';

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
