name: Terraform Plan Analysis

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Parse Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8


    - name: Terraform Init
      run: terraform init
      working-directory: ./example/terraform

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: ./example/terraform

    - name: Parse Terraform Plan
      id: parse
      uses: ./
      with:
        terraform-plan: ${{ steps.plan.outputs.stdout }}
        ignore-resources: '["null_resource.ignored_resource"]'

    - name: Display Results
      run: |
        echo "=== Overall Diff Outputs ==="
        echo "Diff bool: ${{ steps.parse.outputs.diff-bool }}"
        echo "Diff count: ${{ steps.parse.outputs.diff-count }}"
        echo "Diff resources: ${{ steps.parse.outputs.diff-resources }}"
        echo ""
        echo "=== Create Outputs ==="
        echo "Create bool: ${{ steps.parse.outputs.create-bool }}"
        echo "Create count: ${{ steps.parse.outputs.create-count }}"
        echo "Create resources: ${{ steps.parse.outputs.create-resources }}"
        echo ""
        echo "=== Destroy Outputs ==="
        echo "Destroy bool: ${{ steps.parse.outputs.destroy-bool }}"
        echo "Destroy count: ${{ steps.parse.outputs.destroy-count }}"
        echo "Destroy resources: ${{ steps.parse.outputs.destroy-resources }}"
        echo ""
        echo "=== Update Outputs ==="
        echo "Update bool: ${{ steps.parse.outputs.update-bool }}"
        echo "Update count: ${{ steps.parse.outputs.update-count }}"
        echo "Update resources: ${{ steps.parse.outputs.update-resources }}"
        echo ""
        echo "=== Replace Outputs ==="
        echo "Replace bool: ${{ steps.parse.outputs.replace-bool }}"
        echo "Replace count: ${{ steps.parse.outputs.replace-count }}"
        echo "Replace resources: ${{ steps.parse.outputs.replace-resources }}"
        echo ""
        echo "=== JSON Output ==="
        echo '${{ steps.parse.outputs.diff-json }}'
        echo ""
        echo "=== Raw Output ==="
        echo '${{ steps.parse.outputs.diff-raw }}'

    - name: Extract values with jq
      id: extract-jq
      run: |
        DIFF_JSON='${{ steps.parse.outputs.diff-json }}'
        TOTAL_CHANGES=$(echo "$DIFF_JSON" | jq -r '.summary.totalChanges')
        TO_ADD=$(echo "$DIFF_JSON" | jq -r '.summary.toAdd')
        TO_CHANGE=$(echo "$DIFF_JSON" | jq -r '.summary.toChange')
        TO_DESTROY=$(echo "$DIFF_JSON" | jq -r '.summary.toDestroy')
        RESOURCE_COUNT=$(echo "$DIFF_JSON" | jq -r '.resourceCount')

        echo "total-changes=$TOTAL_CHANGES" >> $GITHUB_OUTPUT
        echo "to-add=$TO_ADD" >> $GITHUB_OUTPUT
        echo "to-change=$TO_CHANGE" >> $GITHUB_OUTPUT
        echo "to-destroy=$TO_DESTROY" >> $GITHUB_OUTPUT
        echo "resource-count=$RESOURCE_COUNT" >> $GITHUB_OUTPUT

    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      env:
        DIFF_JSON: ${{ steps.parse.outputs.diff-json }}
      with:
        script: |
          const diffBool = '${{ steps.parse.outputs.diff-bool }}';
          const diffCount = '${{ steps.parse.outputs.diff-count }}';
          const resources = JSON.parse('${{ steps.parse.outputs.diff-resources }}');
          const totalChanges = '${{ steps.extract-jq.outputs.total-changes }}';
          const toAdd = '${{ steps.extract-jq.outputs.to-add }}';
          const toChange = '${{ steps.extract-jq.outputs.to-change }}';
          const toDestroy = '${{ steps.extract-jq.outputs.to-destroy }}';
          const resourceCount = '${{ steps.extract-jq.outputs.resource-count }}';

          // New action-specific outputs
          const createBool = '${{ steps.parse.outputs.create-bool }}';
          const createCount = '${{ steps.parse.outputs.create-count }}';
          const createResources = JSON.parse('${{ steps.parse.outputs.create-resources }}' || '[]');
          const destroyBool = '${{ steps.parse.outputs.destroy-bool }}';
          const destroyCount = '${{ steps.parse.outputs.destroy-count }}';
          const destroyResources = JSON.parse('${{ steps.parse.outputs.destroy-resources }}' || '[]');
          const updateBool = '${{ steps.parse.outputs.update-bool }}';
          const updateCount = '${{ steps.parse.outputs.update-count }}';
          const updateResources = JSON.parse('${{ steps.parse.outputs.update-resources }}' || '[]');
          const replaceBool = '${{ steps.parse.outputs.replace-bool }}';
          const replaceCount = '${{ steps.parse.outputs.replace-count }}';
          const replaceResources = JSON.parse('${{ steps.parse.outputs.replace-resources }}' || '[]');

          let diffJson;
          try {
            diffJson = JSON.parse(process.env.DIFF_JSON);
          } catch (e) {
            console.log('Failed to parse diff-json:', e);
            diffJson = { summary: { toAdd: 0, toChange: 0, toDestroy: 0, totalChanges: 0 }, resources: [] };
          }

          let body = `## Terraform Plan Analysis (${totalChanges} total changes via jq)\n\n`;

          if (diffBool === 'true') {
            body += `✅ **Changes detected** affecting ${diffCount} resources:\n\n`;

            // Action-specific summary
            body += '### Summary by Action\n';
            if (createBool === 'true') {
              body += `- ➕ **Create**: ${createCount} resource(s)\n`;
            }
            if (updateBool === 'true') {
              body += `- 🔄 **Update**: ${updateCount} resource(s)\n`;
            }
            if (replaceBool === 'true') {
              body += `- 🔄 **Replace**: ${replaceCount} resource(s)\n`;
            }
            if (destroyBool === 'true') {
              body += `- ❌ **Destroy**: ${destroyCount} resource(s)\n`;
            }
            body += '\n';

            // Original Changed Resources section
            body += '### Changed Resources\n```\n';
            for (const resource of resources) {
              body += `${resource}\n`;
            }
            body += '```\n\n';

            // Plan Summary
            body += `**Plan Summary**: ${toAdd} to add, ${toChange} to change, ${toDestroy} to destroy\n\n`;

            // Detailed resource changes from diff-json
            body += '### Detailed Resource Changes\n';
            for (const resource of diffJson.resources) {
              const actionEmoji = {
                'create': '➕',
                'update': '🔄',
                'delete': '❌',
                'replace': '🔄'
              }[resource.action] || '🔄';

              body += `${actionEmoji} **${resource.action.toUpperCase()}**: \`${resource.address}\` (${resource.resourceType})\n`;
              body += `   - ${resource.changes.description}\n\n`;
            }
          } else {
            body += '✅ **No changes detected**\n\n';
          }

          // Original Outputs section with new outputs
          body += '### Outputs\n';
          body += `- **diff-bool**: \`${diffBool}\`\n`;
          body += `- **diff-count**: \`${diffCount}\`\n`;
          body += `- **diff-resources**: \`${JSON.stringify(resources)}\`\n`;
          body += `- **create-bool**: \`${createBool}\`, **create-count**: \`${createCount}\`, **create-resources**: \`${JSON.stringify(createResources)}\`\n`;
          body += `- **destroy-bool**: \`${destroyBool}\`, **destroy-count**: \`${destroyCount}\`, **destroy-resources**: \`${JSON.stringify(destroyResources)}\`\n`;
          body += `- **update-bool**: \`${updateBool}\`, **update-count**: \`${updateCount}\`, **update-resources**: \`${JSON.stringify(updateResources)}\`\n`;
          body += `- **replace-bool**: \`${replaceBool}\`, **replace-count**: \`${replaceCount}\`, **replace-resources**: \`${JSON.stringify(replaceResources)}\`\n`;
          body += `- **Plan Summary**: ${diffJson.summary.toAdd} to add, ${diffJson.summary.toChange} to change, ${diffJson.summary.toDestroy} to destroy\n\n`;

          // JSON structure analysis section
          if (diffBool === 'true') {
            body += '### JSON Structure Analysis\n';
            body += `**Plan Summary (jq parsed)**: Total ${totalChanges} changes - ${toAdd} to add, ${toChange} to change, ${toDestroy} to destroy\n\n`;
            body += `**Resource Count (jq parsed)**: ${resourceCount} resources affected\n\n`;

            // Detailed resource changes from diff-json
            body += '### Detailed Resource Changes (from JSON)\n';
            for (const resource of diffJson.resources) {
              const actionEmoji = {
                'create': '➕',
                'update': '🔄',
                'delete': '❌',
                'replace': '🔄'
              }[resource.action] || '🔄';

              body += `${actionEmoji} **${resource.action.toUpperCase()}**: \`${resource.address}\` (${resource.resourceType})\n`;
              body += `   - ${resource.changes.description}\n`;
              if (resource.changes.before !== null) {
                body += `   - Before: \`${resource.changes.before}\`\n`;
              }
              if (resource.changes.after !== null) {
                body += `   - After: \`${resource.changes.after}\`\n`;
              }
              body += '\n';
            }
          }

          // Detailed JSON structure
          body += '### Detailed Analysis (JSON)\n';
          body += '```json\n';
          body += JSON.stringify(diffJson, null, 2);
          body += '\n```\n\n';

          // Raw plan
          const diffRaw = `${{ steps.parse.outputs.diff-raw }}`;
          if (diffRaw && diffRaw.trim()) {
            body += '### Raw Terraform Plan Output\n';
            body += '```\n' + diffRaw + '\n```\n\n';
          }

          body += '---\n*Generated by Terraform Plan Parser*';

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
