name: Terraform Plan Analysis

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Parse Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8


    - name: Terraform Init
      run: terraform init
      working-directory: ./example/terraform

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: ./example/terraform

    - name: Parse Terraform Plan
      id: parse
      uses: ./
      with:
        terraform-plan: ${{ steps.plan.outputs.stdout }}
        ignore-resources: '["null_resource.ignored_resource"]'

    - name: Display Results
      run: |
        echo "Diff bool: ${{ steps.parse.outputs.diff-bool }}"
        echo "Diff count: ${{ steps.parse.outputs.diff-count }}"
        echo "Diff resources: ${{ steps.parse.outputs.diff-resources }}"
        echo "Diff JSON:"
        echo '${{ steps.parse.outputs.diff-json }}'
        echo "Diff raw:"
        echo '${{ steps.parse.outputs.diff-raw }}'

    - name: Comment on PR (if PR)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const diffBool = '${{ steps.parse.outputs.diff-bool }}';
          const diffCount = '${{ steps.parse.outputs.diff-count }}';
          const resources = JSON.parse('${{ steps.parse.outputs.diff-resources }}');
          const diffRaw = `${{ steps.parse.outputs.diff-raw }}`;
          const diffJson = JSON.parse(`${{ steps.parse.outputs.diff-json }}`);

          let body = '## Terraform Plan Analysis\n\n';

          // Summary
          if (diffBool === 'true') {
            body += `✅ **Changes detected** affecting ${diffCount} resources:\n\n`;
            body += '### Changed Resources\n```\n';
            for (const resource of resources) {
              body += `${resource}\n`;
            }
            body += '```\n\n';
          } else {
            body += '✅ **No changes detected**\n\n';
          }

          // All outputs
          body += '### Outputs\n';
          body += `- **diff-bool**: \`${diffBool}\`\n`;
          body += `- **diff-count**: \`${diffCount}\`\n`;
          body += `- **diff-resources**: \`${JSON.stringify(resources)}\`\n`;
          body += `- **Plan Summary**: ${diffJson.summary.toAdd} to add, ${diffJson.summary.toChange} to change, ${diffJson.summary.toDestroy} to destroy\n\n`;

          // Raw plan
          if (diffRaw && diffRaw.trim()) {
            body += '### Raw Terraform Plan Output\n';
            body += '```\n' + diffRaw + '\n```\n\n';
          }

          body += '---\n*Generated by Terraform Plan Parser*';

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
