name: Terraform Plan Analysis

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Parse Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8


    - name: Terraform Init
      run: terraform init
      working-directory: ./example/terraform

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: ./example/terraform

    - name: Parse Terraform Plan
      id: parse
      uses: ./
      with:
        terraform-plan: ${{ steps.plan.outputs.stdout }}
        ignore-resources: '["null_resource.ignored_resource"]'

    - name: Display Results
      run: |
        echo "Diff bool: ${{ steps.parse.outputs.diff-bool }}"
        echo "Diff count: ${{ steps.parse.outputs.diff-count }}"
        echo "Diff resources: ${{ steps.parse.outputs.diff-resources }}"
        echo "Diff JSON:"
        echo '${{ steps.parse.outputs.diff-json }}'
        echo "Diff raw:"
        echo '${{ steps.parse.outputs.diff-raw }}'

    - name: Extract values with jq
      id: extract-jq
      run: |
        DIFF_JSON='${{ steps.parse.outputs.diff-json }}'
        TOTAL_CHANGES=$(echo "$DIFF_JSON" | jq -r '.summary.totalChanges')
        TO_ADD=$(echo "$DIFF_JSON" | jq -r '.summary.toAdd')
        TO_CHANGE=$(echo "$DIFF_JSON" | jq -r '.summary.toChange')
        TO_DESTROY=$(echo "$DIFF_JSON" | jq -r '.summary.toDestroy')
        RESOURCE_COUNT=$(echo "$DIFF_JSON" | jq -r '.resourceCount')

        echo "total-changes=$TOTAL_CHANGES" >> $GITHUB_OUTPUT
        echo "to-add=$TO_ADD" >> $GITHUB_OUTPUT
        echo "to-change=$TO_CHANGE" >> $GITHUB_OUTPUT
        echo "to-destroy=$TO_DESTROY" >> $GITHUB_OUTPUT
        echo "resource-count=$RESOURCE_COUNT" >> $GITHUB_OUTPUT

    - name: Comment on PR (if PR)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      env:
        DIFF_JSON: ${{ steps.parse.outputs.diff-json }}
      with:
        script: |
          const diffBool = '${{ steps.parse.outputs.diff-bool }}';
          const diffCount = '${{ steps.parse.outputs.diff-count }}';
          const resources = JSON.parse('${{ steps.parse.outputs.diff-resources }}');
          const diffRaw = `${{ steps.parse.outputs.diff-raw }}`;

          // jq extracted values
          const totalChanges = '${{ steps.extract-jq.outputs.total-changes }}';
          const toAdd = '${{ steps.extract-jq.outputs.to-add }}';
          const toChange = '${{ steps.extract-jq.outputs.to-change }}';
          const toDestroy = '${{ steps.extract-jq.outputs.to-destroy }}';
          const resourceCount = '${{ steps.extract-jq.outputs.resource-count }}';

          let diffJson;
          try {
            diffJson = JSON.parse(process.env.DIFF_JSON);
          } catch (e) {
            console.log('Failed to parse diff-json:', e);
            diffJson = { summary: { toAdd: 0, toChange: 0, toDestroy: 0, totalChanges: 0 }, resources: [] };
          }

          let body = `## Terraform Plan Analysis (${totalChanges} total changes via jq)\n\n`;

          // Summary
          if (diffBool === 'true') {
            body += `✅ **Changes detected** affecting ${diffCount} resources:\n\n`;

            // Original Changed Resources section
            body += '### Changed Resources\n```\n';
            for (const resource of resources) {
              body += `${resource}\n`;
            }
            body += '```\n\n';
          } else {
            body += '✅ **No changes detected**\n\n';
          }

          // Original Outputs section
          body += '### Outputs\n';
          body += `- **diff-bool**: \`${diffBool}\`\n`;
          body += `- **diff-count**: \`${diffCount}\`\n`;
          body += `- **diff-resources**: \`${JSON.stringify(resources)}\`\n`;
          body += `- **Plan Summary**: ${diffJson.summary.toAdd} to add, ${diffJson.summary.toChange} to change, ${diffJson.summary.toDestroy} to destroy\n\n`;

          // JSON structure analysis section
          if (diffBool === 'true') {
            body += '### JSON Structure Analysis\n';
            body += `**Plan Summary (jq parsed)**: Total ${totalChanges} changes - ${toAdd} to add, ${toChange} to change, ${toDestroy} to destroy\n\n`;
            body += `**Resource Count (jq parsed)**: ${resourceCount} resources affected\n\n`;

            // Detailed resource changes from diff-json
            body += '### Detailed Resource Changes (from JSON)\n';
            for (const resource of diffJson.resources) {
              const actionEmoji = {
                'create': '➕',
                'update': '🔄',
                'delete': '❌',
                'replace': '🔄'
              }[resource.action] || '🔄';

              body += `${actionEmoji} **${resource.action.toUpperCase()}**: \`${resource.address}\` (${resource.resourceType})\n`;
              body += `   - ${resource.changes.description}\n`;
              if (resource.changes.before !== null) {
                body += `   - Before: \`${resource.changes.before}\`\n`;
              }
              if (resource.changes.after !== null) {
                body += `   - After: \`${resource.changes.after}\`\n`;
              }
              body += '\n';
            }
          }

          // Detailed JSON structure
          body += '### Detailed Analysis (JSON)\n';
          body += '```json\n';
          body += JSON.stringify(diffJson, null, 2);
          body += '\n```\n\n';

          // Raw plan
          if (diffRaw && diffRaw.trim()) {
            body += '### Raw Terraform Plan Output\n';
            body += '```\n' + diffRaw + '\n```\n\n';
          }

          body += '---\n*Generated by Terraform Plan Parser*';

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
